version: '2'
services:
  kube-charts-mirror:
    image: kube-charts-mirror:latest
    build: .
    restart: always
    container_name: kube-charts-mirror
    environment:
    - GIT_REPO=${GIT_REPO}
    - GIT_USER_NAME=${GIT_USER_NAME}
    - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    volumes:
    - .:/mnt/charts
